### ISSUE TITLE
moving to gh-pages

### ISSUE THREAD

**Issue by rmg55** [evanwill/workshop-template-b#1]
If I move this to a separate branch in my repository, do I need to change anything specific in the ._config file (or elsewhere) to get it to work... Having some issues getting it to render properly here: https://github.com/rmg55/SCINET-GEOSPATIAL-RESEARCH-WG/tree/gh-pages

**Comment by evanwill** [comment]
@rmg55  sorry I missed this question. 
Looks like you probably figured it out already, but---

Nothing in the code should need to change (just make sure the `url` and `baseurl` are correct).
The demo workshop-template-b is set up building from master branch. However, you could move the template code into a branch named `gh-pages`, in which case it should automatically start building from there. You could also move the code into a folder named `docs` and build it from there. If you go into your repository "Settings" tab, and scroll way down there is a drop down to select your gh-pages branch options. Sometimes I have had hiccups if it was already building from master, then created a gh-pages branch. 

Let me know how the workshop goes!

**Comment by rmg55** [comment]
@evanwill, thanks for the info - I was able to get it to work. For some reason to use the "gh-pages" branch, I had to use the "orphan" option in creating the branch, and then it worked.

Really like the layout/page you have created here - thanks for sharing!
